---
- ansible.builtin.include_tasks: secrets.yml
  tags:
    - jcasc-secrets
  when: jenkins_casc_secrets | length > 0

- ansible.builtin.include_tasks: upload.yml
  tags:
    - jcasc-upload

- ansible.builtin.include_tasks: configure.yml
  tags:
    - jcasc-configure
  when: jenkins_casc_config_path_configure

- name: "trigger reload handler when necessary."
  ansible.builtin.command: /bin/true
  changed_when: true
  when:
    # only trigger when configure result is false, since this will do a implicit reload
    - not ((_jenkins_casc_plugin_configure_result | default({})).changed | default(false))
    # and only trigger reload when upload files have changed or unmanaged files have been deleted
    - (_jenkins_casc_upload_files_result | default({})).changed | default(false) or
      (_jenkins_casc_unmanaged_result | default({})).changed | default(false)
  notify:
    - wcm-io-devops.jenkins_configuration_as_code reload
  tags:
    - skip_ansible_lint
